@echo off
echo Starting backend server...
start cmd /k "cd /d %~dp0 && .\.venv\Scripts\activate && cd backend && python app.py"
echo Starting frontend...
timeout /t 3
start cmd /k "cd /d %~dp0 && .\.venv\Scripts\activate && streamlit run streamlit_app.py"